version: "2"

services:

    waf:
        image: dmgnx/nginx-naxsi
        restart: always
        ports:
            - "80:80"
        links:
            - frontend
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./ssl:/etc/nginx/ssl:ro
            - ./frontend/staticserve:/usr/share/nginx/html/static:ro

    frontend:
        image: jlabusch/wrms-dash-frontend
        restart: always
        build: frontend
        expose:
            - "80"
        environment:
            - DJANGO_DEBUG
            - DJANGO_BACKEND_URI=http://api:80
            - DJANGO_SECRET
        links:
            - "lb:api"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./frontend/db.sqlite3:/opt/db.sqlite3
            - ./frontend/staticserve:/opt/staticserve:ro

    lb:
        image: dockercloud/haproxy
        restart: always
        expose:
            - "80"
        links:
            - api
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    api:
        image: jlabusch/wrms-dash-api
        restart: always
        build: api
        expose:
            - "80"
        links:
            - "api-cache"
        entrypoint:
            - npm
            - start
        environment:
            - ICINGA_BASIC_AUTH
            - DEBUG
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./api/config/default.json:/opt/config/default.json:ro

    api-cache:
        image: jlabusch/wrms-dash-api-cache
        restart: always
        build: api-cache
        expose:
            - "80"
        entrypoint:
            - npm
            - start
        environment:
            - ICINGA_BASIC_AUTH
            - DEBUG
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./api-cache/config/default.json:/opt/config/default.json:ro

